# Generated by Django 4.1.5 on 2024-01-16 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stu_id",
                    models.CharField(max_length=20, unique=True, verbose_name="stu_id"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="stu_first_name"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=50, verbose_name="stu_middle_name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="stu_last_name",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="stu_date_of_birth"
                    ),
                ),
                (
                    "standard",
                    models.IntegerField(
                        choices=[
                            (1, "First"),
                            (2, "Second"),
                            (3, "Three"),
                            (4, "Four"),
                            (5, "Five"),
                            (6, "Six"),
                            (7, "Seven"),
                            (8, "Eight"),
                            (9, "Nine"),
                            (10, "Ten"),
                        ],
                        verbose_name="stu_standard",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=50, null=True, verbose_name="stu_email"
                    ),
                ),
                ("mobile_no", models.BigIntegerField(verbose_name="stu_mobile_no")),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "male"), (1, "female"), (2, "other")],
                        null=True,
                        verbose_name="stu_gender",
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="stu_father_name",
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="stu_mother_name",
                    ),
                ),
                (
                    "parents_contact_no",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="parents_contact_no"
                    ),
                ),
                (
                    "permanent_address",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="stu_permanent_address",
                    ),
                ),
                (
                    "current_address",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="stu_current_address",
                    ),
                ),
                (
                    "country",
                    models.IntegerField(
                        blank=True,
                        default="India",
                        null=True,
                        verbose_name="stu_country",
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Andhra Pradesh"),
                            (2, "Arunachal Pradesh"),
                            (3, "Assam"),
                            (4, "Bihar"),
                            (5, "Chhattisgarh"),
                            (6, "Goa"),
                            (7, "Gujarat"),
                            (8, "Haryana"),
                            (9, "Himachal Pradesh"),
                            (10, "Jharkhand"),
                            (11, "Karnataka"),
                            (12, "Kerala"),
                            (13, "Madhya Pradesh"),
                            (14, "Maharashtra"),
                            (15, "Manipur"),
                            (16, "Meghalaya"),
                            (17, "Mizoram"),
                            (18, "Nagaland"),
                            (19, "Odisha"),
                            (20, "Punjab"),
                            (21, "Rajasthan"),
                            (22, "Sikkim"),
                            (23, "Tamil Nadu"),
                            (24, "Telangana"),
                            (25, "Tripura"),
                            (26, "Uttar Pradesh"),
                            (27, "Uttarakhand"),
                            (28, "West Bengal"),
                            (29, "Andaman and Nicobar Islands"),
                            (30, "Chandigarh"),
                            (31, "Dadra and Nagar Haveli and Daman and Diu"),
                            (32, "Lakshadweep"),
                            (33, "Delhi (National Capital Territory of Delhi)"),
                            (34, "Puducherry"),
                            (35, "Ladakh"),
                            (36, "Jammu and Kashmir"),
                        ],
                        null=True,
                        verbose_name="stu_state",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="stu_city"
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="stu_pin_code",
                    ),
                ),
                ("temp_stu_institute", models.IntegerField()),
                (
                    "stu_institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="institute.institute",
                    ),
                ),
            ],
        ),
    ]
